### ISSUE TITLE
Sign Gui Input

### ISSUE THREAD

**Issue by erkutay07** [CyR1en/CommandPrompter#13]
Add sign guis like hypixel
![image](https://user-images.githubusercontent.com/58345549/87474748-47948d80-c62c-11ea-9390-236a31b038f7.png)

**Comment by CyR1en** [comment]
Is the plugin called Sign GUI Lib? If it is, I'd prefer just using that instead and soft depending on it--or maybe embed into CommandPrompter (if possible).

**Comment by erkutay07** [comment]
> Is the plugin called Sign GUI Lib? If it is, I'd prefer just using that instead and soft depending on it--or maybe embed into CommandPrompter (if possible).

Really dont know which plugin is this, but qkings plugins contains this. (auctionmaster, royaleeconomy)

**Comment by CyR1en** [comment]
SignGUI implemented* at https://github.com/CyR1en/CommandPrompter/commit/e6df3334b867031b33923840eba76b75dcab559e

*Hasn't been tested on versions below 1.17
