### ISSUE TITLE
chatcolor plugins making the result different!!

### ISSUE THREAD

**Issue by Stoiky20** [CyR1en/CommandPrompter#15]
Hello there,

I'm running a server using commandprompter and deluxemenus
The plugin works perfect! But there is one issue sir, so here is it:

If I go into the menu and use commandprompter for a bank command (for example)
/bank deposit <@Say a number> - (just an example), it will work only if I have no chatcolor setted!

So if I use ezcolors https://www.spigotmc.org/resources/1-8-8-1-16-4-ezcolors.69871/ or any other chatcolor setting plugin
and I have a chatcolor selected, when I will do the same thing it will just say the result as a color
for example if I have color red and I say the number 100, the plugin will actually see it as "&c100"

Is it possible to bypass the chatcolor setting or disable it while using this commandprompter?
Do you recommend any good chatcolor plugins which works with commandprompter and does not affect the result?

Thanks

**Comment by CyR1en** [comment]
Resolved on Secundum branch
