### ISSUE TITLE
New possible feature

### ISSUE THREAD

**Issue by dhgameryt** [CyR1en/CommandPrompter#2]
you can add that after writing the argument to a command, automatically execute another command or variso commands with cooldown each, and that when writing cancel you can also execute a command, but that these commands are established on each occasion, that are not always the same already pre-set in the plugin config, this to use it with the chestcommands or deluxemenus

:D

**Comment by dhgameryt** [comment]
this to use it with the chestcommands or deluxemenus

**Comment by CyR1en** [comment]
Can you give me an example of this use case?

**Comment by CyR1en** [comment]
No response from OP, closing.
