### ISSUE TITLE
Color Codes

### ISSUE THREAD

**Issue by abobymotaki** [CyR1en/CommandPrompter#43]
This issue/feature-request was posted in [Spigot](discussion link), but moved here so we can keep track of it.

We need a config option to enable/disable the color codes.

**Comment by CyR1en** [comment]
You can disable input sanitation for a prompt using the `-ds` prompt argument. 

Example:
```
nick <-a Player> <-a -ds Enter nickname>
```
The example above would only remove the input sanitation for the second prompt, not the first prompt.
