### ISSUE TITLE
”Clickable Cancel: false "doesn't seem to work

### ISSUE THREAD

**Issue by Highrii** [CyR1en/CommandPrompter#58]
This issue/feature-request was posted in [Spigot](discussion link), but moved here so we can keep track of it.

# Content
```
”Clickable Cancel: false "doesn't seem to work
i test on paper1.20.4
i try reload and restart server but it seems still have the [X] button on the chat text
i hope you can fix it. it is one of my favorite plugin
```

**Comment by CyR1en** [comment]
Fix with this commit: https://github.com/CyR1en/CommandPrompter/commit/2a89c425df17d2770fde810dfd9df5eb9fdadab7
