### ISSUE TITLE
Strip color codes from inputs

### ISSUE THREAD

**Issue by Intriguing-RC** [CyR1en/CommandPrompter#9]
Hello there,

So, I have an issue that I'm facing where CommandPrompter, where my ChatColor plugin is colliding with CommandPrompter. Basically, what my ChatColor plugin is doing is putting a color code in front of every message. So, if someone were to do a command for CommandPrompter, and they typed "cancel", due to my ChatColor plugin, it would send it as "&7cancel". I was wondering if there was a way around this, or if you could add an option to take out the colorcode when someone submits a CommandPrompt.

Thank you very much.

**Comment by CyR1en** [comment]
Cool, will be on the next update!

**Comment by Intriguing-RC** [comment]
Was this ever added?
